name: Trigger auto deployment for dsssi-frontend-mitarbeiter

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/dsssi-frontend-mitarbeiter-AutoDeployTrigger-8b74a669-6a2c-4ba5-adbb-ac8307bb47e5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DSSSIFRONTENDMITARBEITER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DSSSIFRONTENDMITARBEITER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DSSSIFRONTENDMITARBEITER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: kinosystemcontainerreg.azurecr.io
          registryUsername: ${{ secrets.DSSSIFRONTENDMITARBEITER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DSSSIFRONTENDMITARBEITER_REGISTRY_PASSWORD }}
          containerAppName: dsssi-frontend-mitarbeiter
          resourceGroup: kinosystem
          imageToBuild: kinosystemcontainerreg.azurecr.io/dsssi-frontend-mitarbeiter:${{ github.sha }}
          dockerfilePath: Dockerfile


