# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Dsssi-Mitarbeiterzentrale

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://containersfallstudie.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ae691ee00ae7418cafdad2dc4267f277 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d003c6cb1f514ef3ac70c444f751179b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containersfallstudie.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ae691ee00ae7418cafdad2dc4267f277 }}/frontendmitzentr:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Dsssi-Mitarbeiterzentrale'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e92028aa113b43b18e0414a626d6fa10 }}
        images: 'containersfallstudie.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ae691ee00ae7418cafdad2dc4267f277 }}/frontendmitzentr:${{ github.sha }}'