# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dsssi-mitarbeiter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://kinosystemcontainerreg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ca27496d6ae34f80b3af3dc4c40a2064 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_99c9d5f0ef1a458db1138f6f9dc3398a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kinosystemcontainerreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ca27496d6ae34f80b3af3dc4c40a2064 }}/frontendmitarbeiterzentr:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dsssi-mitarbeiter'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_769ab0cc19d643a1943e5d2a7d5959a9 }}
        images: 'kinosystemcontainerreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ca27496d6ae34f80b3af3dc4c40a2064 }}/frontendmitarbeiterzentr:${{ github.sha }}'